// ANEA customer login, cart and checkout
(function(){
const KEY='anea_cart_v1'; let products=[]; let cart=JSON.parse(localStorage.getItem(KEY)||'[]');
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){localStorage.setItem(KEY,JSON.stringify(cart));renderCart();badge();}
function badge(){const e=$('anea-cart-count');if(e)e.textContent=cart.reduce((n,x)=>n+x.qty,0)}
function modal(id,on=true){$(id).classList.toggle('open',on)}
window.aneaClose=id=>modal(id,false);
async function user(){const r=await db.auth.getUser();return r.data.user||null}
window.aneaOpenAuth=()=>modal('anea-auth-modal');
window.aneaOpenCart=()=>{renderCart();modal('anea-cart-modal')};
window.aneaLogin=async()=>{const m=$('anea-auth-msg');const r=await db.auth.signInWithPassword({email:$('anea-auth-email').value.trim(),password:$('anea-auth-password').value});m.textContent=r.error?r.error.message:'Login successful.';if(!r.error){modal('anea-auth-modal',false);account()}};
window.aneaSignup=async()=>{const m=$('anea-auth-msg'),email=$('anea-auth-email').value.trim(),password=$('anea-auth-password').value;if(password.length<6)return m.textContent='Password must be at least 6 characters.';const r=await db.auth.signUp({email,password,options:{emailRedirectTo:location.href}});m.textContent=r.error?r.error.message:(r.data.session?'Account created.':'Account created. Please confirm your email, then login.');if(r.data.session){modal('anea-auth-modal',false);account()}};
window.aneaLogout=async()=>{await db.auth.signOut();account()};
async function account(){const b=$('anea-account-btn');if(!b)return;const u=await user();b.textContent=u?'Account':'Login';b.onclick=u?()=>{if(confirm('Logout from ANEA JWELS?'))aneaLogout()}:aneaOpenAuth}
function add(p){user().then(u=>{if(!u)return aneaOpenAuth();const x=cart.find(i=>i.id===p.id);if(x)x.qty++;else cart.push({id:p.id,product_id:p.product_id,name:p.name,price:Number(p.price||0),image:p.images?.[0]||'',qty:1});save();aneaOpenCart()})}
window.aneaAddToCart=add;
window.aneaQty=(i,d)=>{cart[i].qty+=d;if(cart[i].qty<=0)cart.splice(i,1);save()};
function renderCart(){const e=$('anea-cart-list');if(!e)return;if(!cart.length){e.innerHTML='<p>Your cart is empty.</p>';return}let s=0;e.innerHTML=cart.map((x,i)=>{s+=x.price*x.qty;return '<div class="anea-cart-item"><img src="'+esc(x.image)+'"><div><b>'+esc(x.name)+'</b><div>'+esc(x.product_id)+'</div><div class="anea-qty"><button onclick="aneaQty('+i+',-1)">−</button>'+x.qty+'<button onclick="aneaQty('+i+',1)">+</button></div></div><b>₹'+(x.price*x.qty).toFixed(2)+'</b></div>'}).join('');$('anea-cart-subtotal').textContent='₹'+s.toFixed(2)}
function subtotal(){return cart.reduce((s,x)=>s+x.price*x.qty,0)}
window.aneaStartCheckout=async()=>{if(!(await user())){modal('anea-cart-modal',false);return aneaOpenAuth()}if(!cart.length)return;const u=await user();$('anea-checkout-account').textContent='Logged in as '+u.email;updateTotal();modal('anea-cart-modal',false);modal('anea-checkout-modal')};
function updateTotal(){const s=subtotal(),d=$('anea-c-state').value==='Kerala'?70:150;$('anea-co-sub').textContent='₹'+s.toFixed(2);$('anea-co-del').textContent='₹'+d.toFixed(2);$('anea-co-total').textContent='₹'+(s+d).toFixed(2)}
window.aneaPlaceOrder=async()=>{const m=$('anea-checkout-msg'),u=await user(),name=$('anea-c-name').value.trim(),phone=$('anea-c-phone').value.trim(),address=$('anea-c-address').value.trim(),city=$('anea-c-city').value.trim(),pin=$('anea-c-pincode').value.trim(),state=$('anea-c-state').value,file=$('anea-payment-file').files[0];if(!u)return m.textContent='Please login first.';if(!name||!phone||!address||!city||!pin||!state||!file)return m.textContent='Please complete delivery details and upload payment screenshot.';if(file.size>5242880)return m.textContent='Payment screenshot must be 5MB or smaller.';const s=subtotal(),d=state==='Kerala'?70:150,total=s+d,orderNo='ANEA-'+Date.now().toString().slice(-8),ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=u.id+'/'+orderNo+'.'+ext;m.textContent='Uploading payment screenshot...';const up=await db.storage.from('payment-screenshots').upload(path,file,{contentType:file.type,upsert:false});if(up.error)return m.textContent='Payment screenshot upload failed: '+up.error.message;m.textContent='Creating order...';const items=cart.map(x=>({product_id:x.product_id,name:x.name,price:x.price,quantity:x.qty,image:x.image}));const r=await db.rpc('place_order',{p_customer:{name,phone,email:u.email,address:address+', '+city+', '+state+' - '+pin},p_delivery:d,p_items:items,p_order_number:orderNo,p_subtotal:s,p_total:total});if(r.error)return m.textContent='Order creation failed: '+r.error.message;const upd=await db.from('orders').update({payment_screenshot_url:path,payment_status:'screenshot submitted',notes:'Payment screenshot: '+path}).eq('id',r.data);if(upd.error)console.warn(upd.error);const lines=items.map(x=>x.name+' x '+x.quantity).join('%0A');const wa='https://wa.me/918089731324?text='+encodeURIComponent('Hi ANEA JWELS, I placed order '+orderNo+'.%0A'+lines+'%0ATotal: ₹'+total.toFixed(2)+'%0APayment screenshot uploaded. Please verify and confirm.');cart=[];save();m.innerHTML='Order submitted: <b>'+esc(orderNo)+'</b><br>Payment pending manual verification.<br><br><a class="btn" href="'+wa+'" target="_blank">Send Order on WhatsApp</a>'};
async function init(){const nav=document.querySelector('.nav');if(nav&&!$('anea-account-btn')){const b=document.createElement('div');b.className='anea-top-actions';b.innerHTML='<button id="anea-account-btn">Login</button><button onclick="aneaOpenCart()">Cart <span id="anea-cart-count" class="anea-badge">0</span></button>';nav.appendChild(b)}account();badge();const r=await db.from('products').select('id,product_id,name,price,images').neq('availability','hidden').order('created_at',{ascending:false});products=r.data||[];const box=$('anea-results');if(box)new MutationObserver(()=>attach()).observe(box,{childList:true,subtree:true});setTimeout(attach,800)}
function attach(){document.querySelectorAll('#anea-results .anea-card').forEach((card,i)=>{if(card.querySelector('.anea-add')||!products[i])return;const b=document.createElement('button');b.className='anea-btn anea-add';b.textContent='Add to Cart';b.onclick=()=>add(products[i]);card.appendChild(b)})}
window.addEventListener('load',init); 
})();